"""Unit tests for :mod:`vibe.policy` — the allow/warn/block write oracle.

The full verdict strings are asserted as **literals transcribed independently**
from ``flow/scripts/detect-context.sh`` (not imported from ``policy``), so a typo
in a block/warn message fails here even in an environment where the parity suite
(which needs ``bash``/``jq``) is skipped.
"""

from __future__ import annotations

import subprocess
import sys

import pytest

from vibe import cursor, policy

# ── Verdict strings, transcribed by hand from detect-context.sh ──────────────
STATE_JSON_BLOCK = "block:state.json is written only via set-state.sh, never by direct edit"


def lessons_block(state: str) -> str:
    return f"block:.spec/lessons.md is writable only during a *.compound state (current: {state})"


def root_spec_block(state: str) -> str:
    return (
        "block:root .spec specs are writable only during strategy.spec or "
        f"feature.compound (current: {state})"
    )


AGENTS_WARN = (
    "warn:CLAUDE.md/AGENTS.md active-rules block is generated by "
    "regen-active-rules.sh; edits inside the markers are overwritten next compound"
)


def source_warn(state: str) -> str:
    return f"warn:source/test edits outside an impl/fix/verify state (current: {state})"


ALL_STATES = [
    "idle",
    "setup.detect",
    "setup.apply",
    "strategy.brainstorm",
    "strategy.spec",
    "strategy.compound",
    "feature.design",
    "feature.plan",
    "feature.impl",
    "feature.verify",
    "feature.compound",
    "quick.triage",
    "quick.fix",
    "quick.verify",
    "amend",
]


# ── Block 3: state.json is writer-only, in every state ───────────────────────
@pytest.mark.parametrize("state", ALL_STATES)
@pytest.mark.parametrize(
    "path",
    [
        ".agents/skills/vibe/state.json",
        "sub/.agents/skills/vibe/state.json",
        "a/b/c/.agents/skills/vibe/state.json",
    ],
)
def test_state_json_always_blocked(path, state):
    assert policy.decide(path, state) == STATE_JSON_BLOCK


# ── Block 1: lessons.md only during *.compound ───────────────────────────────
@pytest.mark.parametrize("state", ["feature.compound", "strategy.compound"])
@pytest.mark.parametrize("path", [".spec/lessons.md", "nested/.spec/lessons.md"])
def test_lessons_allowed_in_compound(path, state):
    assert policy.decide(path, state) == "allow"


@pytest.mark.parametrize(
    "state",
    [s for s in ALL_STATES if s not in {"feature.compound", "strategy.compound"}],
)
@pytest.mark.parametrize("path", [".spec/lessons.md", "nested/.spec/lessons.md"])
def test_lessons_blocked_elsewhere(path, state):
    assert policy.decide(path, state) == lessons_block(state)


def test_lessons_blocked_in_setup_apply():
    # setup.apply relaxes root specs and source, but NOT lessons.
    assert policy.decide(".spec/lessons.md", "setup.apply") == lessons_block("setup.apply")


# ── Block 2: root specs only during strategy.spec / feature.compound / setup.apply
ROOT_SPECS = [".spec/product.md", ".spec/tech.md", ".spec/design.md", ".spec/plan.md"]


@pytest.mark.parametrize("state", ["strategy.spec", "feature.compound", "setup.apply"])
@pytest.mark.parametrize("path", ROOT_SPECS + ["deep/.spec/plan.md"])
def test_root_specs_allowed(path, state):
    assert policy.decide(path, state) == "allow"


@pytest.mark.parametrize(
    "state",
    [s for s in ALL_STATES if s not in {"strategy.spec", "feature.compound", "setup.apply"}],
)
@pytest.mark.parametrize("path", ROOT_SPECS + ["deep/.spec/plan.md"])
def test_root_specs_blocked_elsewhere(path, state):
    assert policy.decide(path, state) == root_spec_block(state)


def test_root_specs_blocked_in_strategy_compound():
    # Discriminator: lessons-allowed has strategy.compound, root specs do NOT.
    assert policy.decide(".spec/plan.md", "strategy.compound") == root_spec_block(
        "strategy.compound"
    )


def test_spec_research_is_not_a_root_block():
    assert policy.decide(".spec/research.md", "idle") == "allow"


# ── Warn: managed CLAUDE.md / AGENTS.md active-rules block ────────────────────
@pytest.mark.parametrize("state", ["idle", "feature.impl", "feature.compound"])
@pytest.mark.parametrize(
    "path", ["CLAUDE.md", "AGENTS.md", "docs/CLAUDE.md", "a/b/AGENTS.md"]
)
def test_agents_docs_always_warn(path, state):
    assert policy.decide(path, state) == AGENTS_WARN


# ── Warn: src / tests outside an impl/fix/verify state ───────────────────────
@pytest.mark.parametrize(
    "state",
    ["feature.impl", "feature.verify", "quick.fix", "quick.verify", "setup.apply"],
)
@pytest.mark.parametrize(
    "path", ["src/vibe/policy.py", "tests/test_x.py", "pkg/src/a.py", "pkg/tests/b.py"]
)
def test_source_allowed_in_impl_states(path, state):
    assert policy.decide(path, state) == "allow"


@pytest.mark.parametrize(
    "state",
    [
        s
        for s in ALL_STATES
        if s
        not in {"feature.impl", "feature.verify", "quick.fix", "quick.verify", "setup.apply"}
    ],
)
@pytest.mark.parametrize(
    "path", ["src/vibe/policy.py", "tests/test_x.py", "pkg/src/a.py", "pkg/tests/b.py"]
)
def test_source_warns_elsewhere(path, state):
    assert policy.decide(path, state) == source_warn(state)


# ── else → allow ─────────────────────────────────────────────────────────────
@pytest.mark.parametrize(
    "path",
    ["README.md", "docs/guide.md", "src", "tests", "flow/scripts/x.sh", "pyproject.toml"],
)
def test_unguarded_paths_allow(path):
    assert policy.decide(path, "idle") == "allow"


def test_bare_src_dir_is_not_a_source_match():
    # ``src/*`` matches ``src/<x>`` but the bare token ``src`` does not.
    assert policy.decide("src", "idle") == "allow"


# ── Leading ``./`` is stripped exactly like ``${path#./}`` ───────────────────
def test_leading_dotslash_stripped_for_block():
    assert policy.decide("./.spec/lessons.md", "idle") == lessons_block("idle")


def test_leading_dotslash_stripped_for_warn():
    assert policy.decide("./src/x.py", "idle") == source_warn("idle")


def test_only_single_leading_dotslash_stripped():
    # ``${path#./}`` strips exactly one prefix: ``.//src/x.py`` → ``/src/x.py``,
    # which still matches the ``*/src/*`` glob (verified against the bash origin).
    assert policy.decide(".//src/x.py", "idle") == source_warn("idle")


# ── State resolved via cursor when omitted (deterministic project_root) ──────
def test_omitted_state_resolves_from_cursor(target_project):
    cpath = cursor.path_for(target_project)
    cursor.write(cpath, "feature.compound")
    assert policy.decide(".spec/lessons.md", project_root=target_project) == "allow"


def test_omitted_state_defaults_to_idle_without_cursor(target_project):
    # No cursor written → resolve_state degrades to idle → lessons blocked.
    assert policy.decide(
        ".spec/lessons.md", project_root=target_project
    ) == lessons_block("idle")


def test_empty_string_state_also_resolves_from_cursor(target_project):
    # Faithful to bash ``${2:-…}``: an empty state triggers cursor resolution.
    cpath = cursor.path_for(target_project)
    cursor.write(cpath, "strategy.spec")
    assert policy.decide(".spec/plan.md", "", project_root=target_project) == "allow"


def test_explicit_state_bypasses_cursor(target_project):
    cpath = cursor.path_for(target_project)
    cursor.write(cpath, "feature.compound")
    # Explicit state wins; the cursor's feature.compound is not consulted.
    assert policy.decide(".spec/lessons.md", "idle", project_root=target_project) == (
        lessons_block("idle")
    )


def test_resolve_state_reads_cursor(target_project):
    cpath = cursor.path_for(target_project)
    cursor.write(cpath, "feature.impl", "demo")
    assert policy.resolve_state(target_project) == "feature.impl"


# ── Hot-path import purity ───────────────────────────────────────────────────
def test_import_pulls_no_typer_rich_pydantic():
    code = (
        "import sys, vibe.policy\n"
        "leaked = {'typer', 'rich', 'pydantic'} & set(sys.modules)\n"
        "assert not leaked, leaked\n"
    )
    result = subprocess.run(
        [sys.executable, "-c", code],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
