#!/usr/bin/env bash
# detect-context.sh — single source of truth for "where are we" and "is this
# write allowed here". Read-only. Two modes:
#
#   detect-context.sh                  # emit a JSON snapshot of the current state
#   detect-context.sh decide <path>    # allow|warn|block for writing <path> now
#   detect-context.sh decide <path> <state>   # ... as if in <state> (testing)
#
# The decision policy lives HERE, once, so every adapter's hook is a thin shell
# that calls this and translates the verdict to its own exit-code convention.
# This houses the future PreToolUse decision fn (Stage 2); in Stage 1 it is the
# canonical reference the skills consult.
#
# The three hard blocks (everything else is allow/warn):
#   1. .spec/lessons.md            — only during a *.compound state
#   2. root .spec/{product,tech,design,plan}.md
#                                  — only during strategy.spec or feature.compound
#   3. .agents/skills/vibe/state.json — never by direct edit; only via set-state.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MACHINE="$SKILL_DIR/state-machine.json"
STATE="$SKILL_DIR/state.json"

have_jq() { command -v jq >/dev/null 2>&1; }

# Resolve the current compound state key from the cursor (default: idle).
current_state() {
  if have_jq && [[ -f "$STATE" ]] && jq -e . "$STATE" >/dev/null 2>&1; then
    local flow phase
    flow=$(jq -r '.flow // "idle"' "$STATE")
    phase=$(jq -r '.phase // "idle"' "$STATE")
    if [[ "$flow" == "$phase" ]]; then echo "$flow"; else echo "$flow.$phase"; fi
  else
    echo "idle"
  fi
}

# ── snapshot mode ────────────────────────────────────────────────────────────
snapshot() {
  local key; key="$(current_state)"
  if ! have_jq; then
    printf '{"state":"%s","jq":false,"note":"jq missing; degraded"}\n' "$key"
    return 0
  fi
  local feature="null"
  [[ -f "$STATE" ]] && feature=$(jq -r '.feature // "null"' "$STATE" 2>/dev/null || echo null)
  jq -n \
    --arg state "$key" \
    --argjson entry "$(jq --arg s "$key" '.states[$s] // {}' "$MACHINE")" \
    --arg feature "$feature" \
    '{
       state: $state,
       feature: (if $feature == "null" then null else $feature end),
       caveman: ($entry.caveman // null),
       skill: ($entry.skill // null),
       delegates: ($entry.delegates // []),
       reads: ($entry.reads // []),
       writes: ($entry.writes // []),
       inject: ($entry.inject // null),
       next: ($entry.next // []),
       exit: ($entry.exit // null)
     }'
}

# ── decision mode ──────────────────────────────────────────────────────────—
# Emits one of: allow | warn:<reason> | block:<reason>
decide() {
  local path="$1"
  local state="${2:-$(current_state)}"

  # Normalise a leading ./
  path="${path#./}"

  # Block 3: state.json is writer-only.
  case "$path" in
    .agents/skills/vibe/state.json|*/.agents/skills/vibe/state.json)
      echo "block:state.json is written only via set-state.sh, never by direct edit"
      return 0
      ;;
  esac

  # Block 1: lessons.md only during a compound state.
  case "$path" in
    .spec/lessons.md|*/.spec/lessons.md)
      case "$state" in
        feature.compound|strategy.compound) echo "allow" ;;
        *) echo "block:.spec/lessons.md is writable only during a *.compound state (current: $state)" ;;
      esac
      return 0
      ;;
  esac

  # Block 2: root specs only during strategy.spec or feature.compound.
  case "$path" in
    .spec/product.md|.spec/tech.md|.spec/design.md|.spec/plan.md|\
*/.spec/product.md|*/.spec/tech.md|*/.spec/design.md|*/.spec/plan.md)
      case "$state" in
        strategy.spec|feature.compound) echo "allow" ;;
        setup.apply) echo "allow" ;;
        *) echo "block:root .spec specs are writable only during strategy.spec or feature.compound (current: $state)" ;;
      esac
      return 0
      ;;
  esac

  # Warning (not a block): the managed active-rules block is generated output.
  case "$path" in
    CLAUDE.md|AGENTS.md|*/CLAUDE.md|*/AGENTS.md)
      echo "warn:CLAUDE.md/AGENTS.md active-rules block is generated by regen-active-rules.sh; edits inside the markers are overwritten next compound"
      return 0
      ;;
  esac

  # Warning: source edits outside an implementation/fix state.
  case "$path" in
    src/*|tests/*|*/src/*|*/tests/*)
      case "$state" in
        feature.impl|feature.verify|quick.fix|quick.verify|setup.apply) echo "allow" ;;
        *) echo "warn:source/test edits outside an impl/fix/verify state (current: $state)" ;;
      esac
      return 0
      ;;
  esac

  echo "allow"
}

case "${1:-}" in
  decide)
    if [[ -z "${2:-}" ]]; then
      echo "usage: detect-context.sh decide <path> [state]" >&2
      exit 1
    fi
    decide "$2" "${3:-}"
    ;;
  ""|snapshot)
    snapshot
    ;;
  *)
    echo "usage: detect-context.sh [snapshot | decide <path> [state]]" >&2
    exit 1
    ;;
esac
